# Generated by Django 4.2.25 on 2025-10-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, verbose_name='БроныИД')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ОплаченоФакт')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='КатегорииИД')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20, verbose_name='Серия')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ПредметИД')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False, verbose_name='УслугаИД')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvision',
            fields=[
                ('provision_id', models.AutoField(primary_key=True, serialize=False, verbose_name='УИД')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('provision_date', models.DateField(verbose_name='Дата оказания услуги')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provisions', to='hotel.booking', verbose_name='Бронирование')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Оказание услуги',
                'verbose_name_plural': 'Оказание услуг',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False, verbose_name='НомерИД')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('room_count', models.IntegerField(verbose_name='Количество комнат')),
                ('bed_count', models.IntegerField(verbose_name='Количество спальных мест')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ГостьИД')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка (%)')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='hotel.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.guest', verbose_name='Гость'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.room', verbose_name='Номер'),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.category', verbose_name='Категория')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Оснащение',
                'verbose_name_plural': 'Оснащение',
                'unique_together': {('category', 'item')},
            },
        ),
    ]
