# Generated by Django 4.2.26 on 2025-12-17 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_guest_user_user_guest_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='guest_profile',
        ),
        migrations.AlterField(
            model_name='guest',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
